#!/bin/bash
set -e

function main() {
  local project_root="$( cd -P "$( dirname -- "$0" )/../.." && pwd )"

  # Inject uid, gid, uname, gname and home for on-the-fly container preparation
  uid="$( id -u )" gid="$( id -g )" \
      uname="$( id -un )" gname="$( id -gn )" home="${HOME}" \
      project_root="${project_root}" \
      docker-compose \
      -p tabula-api-dev \
      -f "${project_root}/dev/docker-compose.yml" \
      $@
}

main "$@"
